### ISSUE TITLE
Kitchen designer pre-launch checklist

### ISSUE THREAD

**Issue by OndrejNepozitek** [OndrejNepozitek/PlateUpMods#1]
- [x] Make it possible to choose a seed
- [x] Add minimum walls count to FE checklist
- [x] Investigate front door missing
- [x] Investigate garden behaviour
- [x] Fix duplicated maps
- [ ] Fix console not being shown by default in Bepinex
- [ ] Fix success message not being hidden after a map is used
- [ ] Handle invalid/empty layouts in FE viewer
